name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: "We do not accept PRs. If you have any questions, please feel free to contact us."
